<a href="https://colab.research.google.com/github/geetika18/Tensorflow-Playground/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook - most fundamental concepts of tensors using tensorflow
1. intro to tensors
2. getting info from tensors
3. manipulating tensors
4. Tensors and numpy
5. using @tf.function(a way to speed up your regular python functions)
6. using gpu using tensorflow


# Introduction to tensors


In [2]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [6]:
#Creating tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# Check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [11]:
# Create a vector
vector = tf.constant([10,10])
vector
#vector.ndim

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
matrix.ndim

2

In [15]:
# Create another matrix
another_matrix = tf.constant([[3.,4.,5.],[6.,7.,8.],[1.,2.,3.]], dtype= tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[3., 4., 5.],
       [6., 7., 8.],
       [1., 2., 3.]], dtype=float16)>

In [16]:
another_matrix.ndim

2

In [19]:
#let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [20]:
tensor.ndim

3

What we have created so far:
* Scalar- a single number
* Vector- a number with direction
* Matrix - a 2D array of numbers
* Tensor - a N-dimensional array of numbers( where N can be any number)

### Creating tensors with tf.variable()

In [22]:
# Create same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [25]:
# Let's try changing the changeable tensor
#changeable_tensor[0] = 9 - wrong way
changeable_tensor[0].assign(9)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [28]:
#let's change the unchangeable tensor

#unchangeable_tensor[0].assign(9)
#unchangeable_tensor
#it won't change - variable tensor are changeabble and constant are not changeable

### Creating Random tensors

Random tensors are tensors of some arbitrary size which contain random numbers
