<a href="https://colab.research.google.com/github/geetika18/Tensorflow-Playground/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook - most fundamental concepts of tensors using tensorflow
1. intro to tensors
2. getting info from tensors
3. manipulating tensors
4. Tensors and numpy
5. using @tf.function(a way to speed up your regular python functions
6. using gpu using tensorflow


# Introduction to tensors


In [2]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [6]:
#Creating tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# Check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [11]:
# Create a vector
vector = tf.constant([10,10])
vector
#vector.ndim

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
matrix.ndim

2