<a href="https://colab.research.google.com/github/geetika18/Tensorflow-Playground/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook - most fundamental concepts of tensors using tensorflow
1. intro to tensors
2. getting info from tensors
3. manipulating tensors
4. Tensors and numpy
5. using @tf.function(a way to speed up your regular python functions)
6. using gpu using tensorflow


# Introduction to tensors


In [2]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [3]:
#Creating tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector
#vector.ndim

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[3.,4.,5.],[6.,7.,8.],[1.,2.,3.]], dtype= tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[3., 4., 5.],
       [6., 7., 8.],
       [1., 2., 3.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
#let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we have created so far:
* Scalar- a single number
* Vector- a number with direction
* Matrix - a 2D array of numbers
* Tensor - a N-dimensional array of numbers( where N can be any number)

### Creating tensors with tf.variable()

In [12]:
# Create same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's try changing the changeable tensor
#changeable_tensor[0] = 9 - wrong way
changeable_tensor[0].assign(9)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [14]:
#let's change the unchangeable tensor

#unchangeable_tensor[0].assign(9)
#unchangeable_tensor
#it won't change - variable tensor are changeabble and constant are not changeable

### Creating Random tensors

Random tensors are tensors of some arbitrary size which contain random numbers


In [15]:
#create two random tensor
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))

random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape = (3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle the order of tensor

In [16]:
#shuffle the tensor(for learning better)
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])
not_shuffled.ndim
tf.random.shuffle(not_shuffled)



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

In [17]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [18]:
#exercise : tensorflow random seed generation

tensor_1 = tf.constant([[3,4],[7,8],[9,0]])
tensor_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [7, 8],
       [9, 0]], dtype=int32)>

In [19]:
#to get the same shuffled use the global seed like this below(global seed and operation seed both)
tf.random.set_seed(42)
tf.random.shuffle(tensor_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 8],
       [9, 0],
       [3, 4]], dtype=int32)>

### Other ways to create tensors



In [20]:
#create tensors of all ones
tf.ones([9,3], tf.int32) # by default it makes float
#create tensors of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Numpy arrays into Tensors

In [21]:
#turn numpy arrays in tensors ( numpy arrays vs tensors - tensors can be run on gpus )
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A, shape = (2,3,4))
B = tf.constant(numpy_A)
A, B, A.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 3)

### Getting information from tensors
*  Shape
*  Rank - ndim
*  Axis or dimension
*  Size



In [23]:
rank_4_tensor = tf.zeros(shape= (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor[-1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor).numpy()
                                  

(TensorShape([2, 3, 4, 5]), 4, 120)

### Indexing the tensors 

In [26]:
# Get first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2] # JUST LIKE PYTHON LISTS

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1, :]
#rank_4_tensor[:1,:3, :2, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
#Create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],[1,2]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [29]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

In [30]:
rank_2_tensor[:2,:1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [ 1]], dtype=int32)>

In [31]:
#add new dimension to the tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [34]:
#alternative
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [36]:
rank_2_tensor #doesnt change the actual tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

### Manipulating tensors with basic operations

**Basic operations**

In [45]:
tensor = tf.constant([[1,7],[3,4]])
tensor + 2
tensor - 2
tensor * 2
tensor / 2
tensor ** 2
tensor

#original tensor is unchanged unlike (tensor = tensor + 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 7],
       [3, 4]], dtype=int32)>

In [48]:
# using tensorflow built in functions
tf.multiply(tensor , 10)
tf.add(tensor , 1)
#tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 8],
       [4, 5]], dtype=int32)>

**Matrix multiplication**


*   tf.matmul
*   tf.tensordot
*   @



In [51]:
#tf.linalg.matmul
A = tf.constant([[1,2],[3,4]])

tf.matmul(A,A)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [53]:
A * A # element wise


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [56]:
A = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
B = tf.constant([[3,5],[6,7],[1,8]])
tf.matmul(A, B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [57]:
# matrix multiplication using @ (python in built)
A @ B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [58]:
# diff shaoes matrix
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])

In [59]:
#lets change the shape of Y 
tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [62]:
tf.matmul(X, tf.reshape(Y , shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [64]:
#can do same things using transpose but results will be diff

tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [65]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [68]:
# tf.tensordot
tf.tensordot(X, tf.transpose(Y), axes =0 )

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 7,  9, 11],
         [ 8, 10, 12]],

        [[14, 18, 22],
         [16, 20, 24]]],


       [[[21, 27, 33],
         [24, 30, 36]],

        [[28, 36, 44],
         [32, 40, 48]]],


       [[[35, 45, 55],
         [40, 50, 60]],

        [[42, 54, 66],
         [48, 60, 72]]]], dtype=int32)>