<a href="https://colab.research.google.com/github/geetika18/Tensorflow-Playground/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook - most fundamental concepts of tensors using tensorflow
1. intro to tensors
2. getting info from tensors
3. manipulating tensors
4. Tensors and numpy
5. using @tf.function(a way to speed up your regular python functions)
6. using gpu using tensorflow


# Introduction to tensors


In [ ]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
#Creating tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector
#vector.ndim

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[3.,4.,5.],[6.,7.,8.],[1.,2.,3.]], dtype= tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[3., 4., 5.],
       [6., 7., 8.],
       [1., 2., 3.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we have created so far:
* Scalar- a single number
* Vector- a number with direction
* Matrix - a 2D array of numbers
* Tensor - a N-dimensional array of numbers( where N can be any number)

### Creating tensors with tf.variable()

In [ ]:
# Create same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try changing the changeable tensor
#changeable_tensor[0] = 9 - wrong way
changeable_tensor[0].assign(9)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [ ]:
#let's change the unchangeable tensor

#unchangeable_tensor[0].assign(9)
#unchangeable_tensor
#it won't change - variable tensor are changeabble and constant are not changeable

### Creating Random tensors

Random tensors are tensors of some arbitrary size which contain random numbers


In [ ]:
#create two random tensor
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))

random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape = (3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.2878567 ],
        [-0.8757901 , -0.08857017],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle the order of tensor

In [ ]:
#shuffle the tensor(for learning better)
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])
not_shuffled.ndim
tf.random.shuffle(not_shuffled)



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
#exercise : tensorflow random seed generation

tensor_1 = tf.constant([[3,4],[7,8],[9,0]])
tensor_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [7, 8],
       [9, 0]], dtype=int32)>

In [ ]:
#to get the same shuffled use the global seed like this below(global seed and operation seed both)
tf.random.set_seed(42)
tf.random.shuffle(tensor_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[7, 8],
       [9, 0],
       [3, 4]], dtype=int32)>

### Other ways to create tensors



In [ ]:
#create tensors of all ones
tf.ones([9,3], tf.int32) # by default it makes float
#create tensors of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Numpy arrays into Tensors

In [ ]:
#turn numpy arrays in tensors ( numpy arrays vs tensors - tensors can be run on gpus )
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape = (2,3,4))
B = tf.constant(numpy_A)
A, B, A.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 3)

### Getting information from tensors
*  Shape
*  Rank - ndim
*  Axis or dimension
*  Size



In [ ]:
rank_4_tensor = tf.zeros(shape= (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[-1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor).numpy()
                                  

(TensorShape([2, 3, 4, 5]), 4, 120)

### Indexing the tensors 

In [ ]:
# Get first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2] # JUST LIKE PYTHON LISTS

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1, :]
#rank_4_tensor[:1,:3, :2, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],[1,2]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

In [ ]:
rank_2_tensor[:2,:1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[10],
       [ 1]], dtype=int32)>

In [ ]:
#add new dimension to the tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [ ]:
#alternative
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [ ]:
rank_2_tensor #doesnt change the actual tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

### Manipulating tensors with basic operations

**Basic operations**

In [ ]:
tensor = tf.constant([[1,7],[3,4]])
tensor + 2
tensor - 2
tensor * 2
tensor / 2
tensor ** 2
tensor

#original tensor is unchanged unlike (tensor = tensor + 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 7],
       [3, 4]], dtype=int32)>

In [ ]:
# using tensorflow built in functions
tf.multiply(tensor , 10)
tf.add(tensor , 1)
#tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 8],
       [4, 5]], dtype=int32)>

**Matrix multiplication**


*   tf.matmul
*   tf.tensordot
*   @



In [ ]:
#tf.linalg.matmul
A = tf.constant([[1,2],[3,4]])

tf.matmul(A,A)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
A * A # element wise


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [ ]:
A = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
B = tf.constant([[3,5],[6,7],[1,8]])
tf.matmul(A, B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# matrix multiplication using @ (python in built)
A @ B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# diff shaoes matrix
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])

In [ ]:
#lets change the shape of Y 
tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y , shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#can do same things using transpose but results will be diff

tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# tf.tensordot
tf.tensordot(X, tf.transpose(Y), axes =0 )

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 7,  9, 11],
         [ 8, 10, 12]],

        [[14, 18, 22],
         [16, 20, 24]]],


       [[[21, 27, 33],
         [24, 30, 36]],

        [[28, 36, 44],
         [32, 40, 48]]],


       [[[35, 45, 55],
         [40, 50, 60]],

        [[42, 54, 66],
         [48, 60, 72]]]], dtype=int32)>

In [ ]:
# changing datatyoes of tensors
B = tf.constant([1,7,4,3])
C = tf.constant([1.2,3.2,4.1])
B.dtype, C.dtype

(tf.int32, tf.float32)

In [ ]:
# change the dtype
C = tf.cast(C,dtype=tf.float16)
C

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.2, 3.2, 4.1], dtype=float16)>

In [ ]:
 E = tf.cast(B,dtype = tf.float32)
 E,B
 

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 7., 4., 3.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 7, 4, 3], dtype=int32)>)

# Aggregating tensors


Aggregating tensors means condensing them from multiple values down to a smaller amount of values

In [ ]:
# Getting the absolute value
D = tf.constant([-4,-5,-6,-10])
tf.abs(D), D

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4,  5,  6, 10], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([ -4,  -5,  -6, -10], dtype=int32)>)

In [ ]:
# following are ways of aggregation 
# 1. Get the minimum 
R = tf.constant(np.random.randint(0,100, size = 50))
R
#smallest_D = tf.minimum(D)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([39, 86, 15, 11, 53, 42, 86, 52, 51, 26, 59, 81, 14,  7, 13, 99,  3,
       31, 45, 93, 88, 12, 78, 27, 86, 35, 49, 91, 95, 13, 17, 91, 84, 48,
       96, 45, 51, 63, 46, 60, 51, 16, 24, 20, 86, 49, 90, 59, 61,  1])>

In [ ]:
# find minimum
tf.reduce_min(R)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# find maximum
print(tf.reduce_max(R))
# find mean
print(tf.reduce_mean(R))
# find sum
print(tf.reduce_sum(R))


tf.Tensor(99, shape=(), dtype=int64)
tf.Tensor(50, shape=(), dtype=int64)
tf.Tensor(2538, shape=(), dtype=int64)


In [ ]:
# find variance
import tensorflow_probability as tfp

print(tfp.stats.variance(E))
print(tfp.stats.stddev(E))
print(tf.math.reduce_std(tf.cast(R, dtype=tf.float32)))
print(tf.math.reduce_variance(tf.cast(R, dtype=tf.float32)))


# Note standard deviations and variance we need tensorflow probability library.. tf.reduce_variance wont work

tf.Tensor(4.6875, shape=(), dtype=float32)
tf.Tensor(2.1650634, shape=(), dtype=float32)
tf.Tensor(29.62199, shape=(), dtype=float32)
tf.Tensor(877.46234, shape=(), dtype=float32)


# finding positional minimum and maximum

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# at what index maximum value exist
tf.argmax(F), F[tf.argmax(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# what position minimum value exists
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Remoivng all single dimensions( Sequeezing a tensor)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (2,1,1,25))
G

<tf.Tensor: shape=(2, 1, 1, 25), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ]]],


       [[[0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [ ]:
G.shape


TensorShape([2, 1, 1, 25])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
         0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
         0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
         0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
         0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
        [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
         0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
         0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
         0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
         0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
       dtype=float32)>, TensorShape([2, 25]))

# on hot encoding tensors

In [ ]:
# create a list of indices
some_list = [0,1,2,3] # could be red green blue white

#one hot encode our list 
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom values for one hot encoding
tf.one_hot(some_list , depth = 4, on_value="hello", off_value="bye bye")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'hello', b'bye bye', b'bye bye', b'bye bye'],
       [b'bye bye', b'hello', b'bye bye', b'bye bye'],
       [b'bye bye', b'bye bye', b'hello', b'bye bye'],
       [b'bye bye', b'bye bye', b'bye bye', b'hello']], dtype=object)>

#  few common math functions


In [ ]:
# create a new tensor 
H = tf.range(1,10)
I = tf.square(H)
J = tf.math.sqrt(tf.cast(H, dtype=tf.float32)) # method requires non int type
K = tf.math.log(tf.cast(H, dtype=tf.float32))

H,I,J,K

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
        2.6457512, 2.828427 , 3.       ], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246], dtype=float32)>)

# Tensors and NumPy

In [ ]:
# create a tensor using numpy array
J = tf.constant(np.array([1,7,3,10]))
I = np.array([1,3,2,4])
#convert our tensor back to a numpy array
J,type(I),np.array(J), type(np.array(J))

(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 1,  7,  3, 10])>,
 numpy.ndarray,
 array([ 1,  7,  3, 10]),
 numpy.ndarray)

In [ ]:
# convert tensor to numpy - other way
J.numpy()


array([ 1,  7,  3, 10])

In [ ]:
# default types of each are slightly diff
numpy_J = tf.constant(np.array([1,3,2,4]))
tensor_J = tf.constant([1,3,2,4])
#check types
numpy_J.dtype, tensor_J.dtype

(tf.int64, tf.int32)

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]